baseurl: "https://schoolfaqs.github.io"
title: SchoolFAQs
theme: 
languageCode: en-us
copyright: SchoolFAQs

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

author:
  name: SchoolFAQs
  profile: "https://www.linkedin.com/company/schoolfaqs"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: SchoolFAQs
  description: Education Platform made for students by students.
  github: "https://github.com/SchoolFAQs"
  linkedin: "https://www.linkedin.com/company/schoolfaqs"
  email: "contact@schoolfaqs.net"
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: true
  dateFormat: "Mon, Jan 2, 2006"
  readingTime: true
  readingTimeText: "Reading time:"


permalinks:
  post: "/:slug/"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Gallery
      url: /gallery
      weight: 2

